// Generates src/data/books.js from the parent site's data.js (run: node gen-data.mjs)
import fs from "node:fs";
import vm from "node:vm";

const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync("../data.js", "utf8"), ctx);
const CATS = ctx.window.CATEGORIES;
const BOOKS = ctx.window.BOOKS;

const catMap = Object.fromEntries(CATS.map((c) => [c.id, c.name]));

// Where book files live:
//  - dev: the /books middleware streams them from the repo root (vite.config.js)
//  - production: set PDF_BASE to the GitHub release download URL; assets there
//    are named <bookId>.<ext> (see ../stage-books.mjs)
const PDF_BASE = process.env.PDF_BASE || "";
const extOf = (p) => (p.match(/\.[^./]+$/) || [""])[0].toLowerCase();
const pdfUrl = (p, i) =>
  PDF_BASE ? `${PDF_BASE}${i}${extOf(p)}` : "/books/" + p.split("/").map(encodeURIComponent).join("/");

const books = BOOKS.map((b, i) => ({
  id: i,
  title: b.title,
  author: b.author || "",
  cat: b.cat,
  category: catMap[b.cat],
  size: b.size || 0,
  cover: `covers/${i}.jpg`, // relative → works at "/" in dev and under /repo/ on Pages
  pdf: pdfUrl(b.path, i),
}));

// Which covers exist as real book covers → nice for the floating hero cards.
const has = (i) => fs.existsSync(`public/covers/${i}.jpg`);
const featuredIds = [2, 5, 11, 4, 28, 20, 55, 18].filter(has);

const positions = [
  { pos: "left-[6%] top-[16%]", depth: 46, delay: 0.1, duration: 6.5, w: "w-24 lg:w-32", rot: -8 },
  { pos: "right-[8%] top-[12%]", depth: -60, delay: 0.25, duration: 7.5, w: "w-28 lg:w-36", rot: 7 },
  { pos: "left-[10%] bottom-[12%]", depth: 38, delay: 0.4, duration: 8, w: "w-24 lg:w-28", rot: 6 },
  { pos: "right-[6%] bottom-[16%]", depth: -44, delay: 0.15, duration: 7, w: "w-28 lg:w-36", rot: -6 },
  { pos: "left-[22%] top-[8%]", depth: 26, delay: 0.5, duration: 9, w: "w-20 lg:w-24", rot: 4 },
  { pos: "right-[22%] bottom-[8%]", depth: -30, delay: 0.35, duration: 8.5, w: "w-20 lg:w-24", rot: -5 },
  { pos: "right-[30%] top-[10%]", depth: 20, delay: 0.6, duration: 9.5, w: "w-16 lg:w-20", rot: 8 },
  { pos: "left-[32%] bottom-[10%]", depth: -22, delay: 0.45, duration: 10, w: "w-16 lg:w-20", rot: -7 },
];

const floating = featuredIds.map((id, k) => ({
  id,
  title: books[id].title,
  cover: books[id].cover,
  ...positions[k % positions.length],
}));

const out = `// AUTO-GENERATED by gen-data.mjs — do not edit by hand.
export const categories = ${JSON.stringify(CATS.map((c) => ({ id: c.id, name: c.name })), null, 2)};

export const books = ${JSON.stringify(books, null, 2)};

export const floatingBooks = ${JSON.stringify(floating, null, 2)};

export const stats = {
  resources: ${books.length},
  categories: ${CATS.length},
  gb: ${(BOOKS.reduce((s, b) => s + (b.size || 0), 0) / 1073741824).toFixed(1)},
};
`;

fs.mkdirSync("src/data", { recursive: true });
fs.writeFileSync("src/data/books.js", out);
console.log(`Wrote src/data/books.js — ${books.length} books, ${floating.length} floating cards.`);
